-- CREATE DATABASE IF NOT EXISTS `hello_app`;

-- CREATE TABLE IF NOT EXISTS `user` (
--   `id` INT UNSIGNED AUTO_INCREMENT,
--   `name` VARCHAR(10) NOT NULL,
--   `password` VARCHAR(20) NOT NULL,
--   `avatar` VARCHAR(500) NOT NULL,
--   `last_login_time` TIMESTAMP NOT NULL,
--   `account` VARCHAR(255) NOT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE (`account`)
-- )ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CREATE TABLE IF NOT EXISTS `friend` (
--   `id` INT UNSIGNED AUTO_INCREMENT,
--   `user_a_id` INT UNSIGNED NOT NULL,
--   `user_b_id` INT UNSIGNED NOT NULL,
--   `user_c_id` INT UNSIGNED NOT NULL,
--   `send_user_id` INT UNSIGNED NOT NULL,
--   `note` VARCHAR(500),
--   `grou_id` INT UNSIGNED,
--   `is_top` INT UNSIGNED NOT NULL,
--   `is_bottom` INT UNSIGNED NOT NULL,
--   `type` INT UNSIGNED NOT NULL,
-- )ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CREATE TABLE IF NOT EXISTS `message` (
--   `id` INT UNSIGNED AUTO_INCREMENT,
--   `from` INT UNSIGNED NOT NULL,
--   `to` INT UNSIGNED NOT NULL,
--   `at` TIMESTAMP NOT NULL,
--   `type` INT UNSIGNED NOT NULL,
--   `text` TEXT NOT NULL,
--   `is_read` INT UNSIGNED NOT NULL,
--   `target` INT UNSIGNED NOT NULL,
-- )
