export const THEME_MODE_LOCAL_STORAGE_KEY = '__HELLO__THEME_MODE_KEY';
export const THEME_MODE_ATTR = 'theme-mode';

export const BRAND_COLOR_LOCAL_STORAGE_KEY = '__HELLO__BRAND_COLOR_KEY';
export const DEFAULT_BRAND_COLOR = '#128C7E';

export const ACCESS_TOKEN_LOCAL_STORAGE_KEY = '__HELLO__ACCESS_TOKEN_KEY';
